# Generated by Django 5.0.7 on 2024-08-02 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='ratings',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], max_length=2),
        ),
        migrations.AlterField(
            model_name='movie',
            name='reviewer_emailId',
            field=models.CharField(max_length=100),
        ),
    ]
